color:
  brandColors:
    - '#FFFFFF'
    - '#FFFF00'
    - '#3BA7FF'
    - '#000008'
    - '#1966B8'
  brandStrength: 0.673142
  lightness: 0.30152
  rhythmicContrast: 0.624155
  saturation: 0.475507
layout_spectrum: 0.945946
name: Bwaz Spot
typography_spectrum: 0.654561
