name: Bwaz Spot
layout_spectrum: 0.380912
typography_spectrum: 0.654561
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.23138443380594254
  lightness: 0.8612595701124519
  saturation: 0.4341613450087607
  rhythmicContrast: 0.1115522962063551
title: ''
author:
  name: 'Mike Boisvert '
  url: ''
  email: bwaz99@gmail.com
content_rating:
  adult: false
