color:
  brandColors:
    - '#16170F'
    - '#FEFEFC'
    - '#D7D7CF'
    - '#959190'
    - '#5B5754'
  brandStrength: 0.342061
  lightness: 0.356419
  rhythmicContrast: 0.690878
  saturation: 0.060853
layout_spectrum: 0.938345
name: Bwaz Spot
typography_spectrum: 0.349662
