color:
  brandColors:
    - '#FFFFFF'
    - '#FFFF00'
    - '#3BA7FF'
    - '#000008'
    - '#1966B8'
  brandStrength: 0.342061
  lightness: 0.356419
  rhythmicContrast: 0.690878
  saturation: 0.060853
layout_spectrum: 0.938345
name: Bwaz Spot
typography_spectrum: 0.349662
